### ISSUE TITLE
Improve navigation options

### ISSUE THREAD

**Issue by jinchuika** [nathaneastwood/fablore#1]
As it is right now, the sidebar buttons and links are somewhat hard to click because they are too small. Links on text only enable when ever that section is open, but not otherwise.

**Comment by nathaneastwood** [comment]
Thanks for the feedback. I'm also not entirely happy with the sidebar. I'll take a look at the mdBook options otherwise I may have to fiddle around with some of the CSS.

**Comment by nathaneastwood** [comment]
@jinchuika I have now turned each of the non-clickable sidebar options into clickable ones. Previously I had been using "draft chapters" which are non-linkable in order to separate out the content. Now I just have a small README which I can link to for those chapters or in some cases I have moved content into those chapters. This should now be easier to navigate at least.
